/**
 * CARWO GOBSAN Static Data
 * 60 Products across 6 categories with AI-generated images
 */

export const products = [
  // ===== COOKWARE (10 products) =====
  {
    id: "cw-001",
    name_en: "Non-Stick Frying Pan",
    name_so: "Dhiso Albaabada Ah",
    description_en: "Premium non-stick frying pan with ceramic coating and heat-resistant handle. Perfect for everyday cooking.",
    description_so: "Dhiso albaabada ah oo tayo sare leh, xidid kululeyska leh. Ku habboon cunto karinta maalin kasta.",
    price: 35.00,
    image: "/images/products/cookware/non-stick-frying-pan.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 25,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 128,
    originalPrice: 45.00,
  },
  {
    id: "cw-002",
    name_en: "Stainless Steel Saucepan",
    name_so: "Dhisdada Birta Ah",
    description_en: "Premium stainless steel saucepan with glass lid. Polished mirror finish for professional cooking.",
    description_so: "Dhisdada birta ah oo tayo sare leh, lakabaya dhalo. Mid adag oo mashiinka dharka lagu dhaqdo.",
    price: 42.00,
    image: "/images/products/cookware/stainless-steel-saucepan.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 18,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 89,
    originalPrice: 55.00,
  },
  {
    id: "cw-003",
    name_en: "Pressure Cooker 6L",
    name_so: "Qabka Cuntada Degdeg",
    description_en: "Modern electric pressure cooker with multiple safety features. Cooks meals 70% faster.",
    description_so: "Qabka cuntada elektarooniga oo leh hawl degdeg. Cunto karinta 70% degdeg.",
    price: 85.00,
    image: "/images/products/cookware/pressure-cooker.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 12,
    featured: true,
    active: true,
    rating: 4.9,
    reviewCount: 156,
    originalPrice: 110.00,
  },
  {
    id: "cw-004",
    name_en: "Cast Iron Skillet",
    name_so: "Dhisdada Birta Madow",
    description_en: "Heavy-duty cast iron skillet with seasoned surface. Perfect for searing and frying.",
    description_so: "Dhisdada birta madow oo mid adag. Ku habboon cunto karinta iyo dhisidda.",
    price: 48.00,
    image: "/images/products/cookware/cast-iron-skillet.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 20,
    featured: false,
    active: true,
    rating: 4.7,
    reviewCount: 203,
    originalPrice: 60.00,
  },
  {
    id: "cw-005",
    name_en: "Stock Pot 8L",
    name_so: "Dhisdada Wayn",
    description_en: "Large stainless steel stock pot with lid. Perfect for soups, stews, and large family meals.",
    description_so: "Dhisdada wayn oo birta ah, lakabaya dhalo. Ku habboon cuntada qoyska.",
    price: 65.00,
    image: "/images/products/cookware/stock-pot.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 15,
    featured: false,
    active: true,
    rating: 4.6,
    reviewCount: 78,
    originalPrice: 80.00,
  },
  {
    id: "cw-006",
    name_en: "Carbon Steel Wok",
    name_so: "Wokka Birta Ah",
    description_en: "Traditional carbon steel wok with wooden handle. Perfect for Asian stir-fry cooking.",
    description_so: "Wokka birta ah oo xidid geed leh. Ku habboon cunto Asiya.",
    price: 38.00,
    image: "/images/products/cookware/carbon-steel-wok.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 22,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 95,
    originalPrice: 48.00,
  },
  {
    id: "cw-007",
    name_en: "Saucepan Set 3-Piece",
    name_so: "Dhisdada 3 Qaybood",
    description_en: "Set of 3 nested saucepans with lids. Different sizes for versatile cooking.",
    description_so: "Dhisdada 3 qaybood oo lakabaya dhalo. Qaybo kala duwan oo ku habboon cunto karinta.",
    price: 75.00,
    image: "/images/products/cookware/saucepan-set.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 10,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 134,
    originalPrice: 95.00,
  },
  {
    id: "cw-008",
    name_en: "Grill Pan Square",
    name_so: "Dhisdada Barxadda",
    description_en: "Square grill pan with ridges for perfect grilling marks. Non-stick surface.",
    description_so: "Dhisdada barxadda oo leh ridges. Ku habboon cunto barxadda.",
    price: 32.00,
    image: "/images/products/cookware/grill-pan.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 18,
    featured: false,
    active: true,
    rating: 4.3,
    reviewCount: 67,
    originalPrice: 40.00,
  },
  {
    id: "cw-009",
    name_en: "Enameled Dutch Oven",
    name_so: "Dhisdada Dhalada Ah",
    description_en: "Enameled cast iron Dutch oven in red. Perfect for slow cooking and baking.",
    description_so: "Dhisdada dhalada ah oo birta ah. Ku habboon cunto karinta degdeg.",
    price: 95.00,
    image: "/images/products/cookware/enameled-dutch-oven.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 8,
    featured: true,
    active: true,
    rating: 4.9,
    reviewCount: 189,
    originalPrice: 125.00,
  },
  {
    id: "cw-010",
    name_en: "Steamer Pot 2-Tier",
    name_so: "Qabka Bariiska",
    description_en: "2-tier stainless steel steamer pot. Healthy cooking with steam technology.",
    description_so: "Qabka bariiska oo 2 qaybood ah. Cunto karinta oo caafimaad leh.",
    price: 55.00,
    image: "/images/products/cookware/steamer-pot.png",
    category_id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    category: "Cookware",
    stock: 14,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 112,
    originalPrice: 70.00,
  },

  // ===== SMALL APPLIANCES (10 products) =====
  {
    id: "sa-001",
    name_en: "Electric Kettle 1.7L",
    name_so: "Dhisi Elektarooniga 1.7L",
    description_en: "Modern electric kettle with LED temperature display. Fast boiling in 90 seconds.",
    description_so: "Dhisi elektarooniga oo leh display kululeyska. Degdeg 90 ilbiriqsi.",
    price: 35.00,
    image: "/images/products/small-appliances/electric-kettle.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 30,
    featured: true,
    active: true,
    rating: 4.7,
    reviewCount: 215,
    originalPrice: 45.00,
  },
  {
    id: "sa-002",
    name_en: "High-Speed Blender",
    name_so: "Mixerka Degdeg",
    description_en: "Professional high-speed blender with 1200W motor. Perfect for smoothies and shakes.",
    description_so: "Mixerka degdeg oo leh motor 1200W. Ku habboon smoothies iyo shakes.",
    price: 65.00,
    image: "/images/products/small-appliances/high-speed-blender.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 15,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 167,
    originalPrice: 85.00,
  },
  {
    id: "sa-003",
    name_en: "Retro Toaster 2-Slice",
    name_so: "Toasterka Retro",
    description_en: "Retro-style toaster with wide slots. Perfect for bagels and thick bread.",
    description_so: "Toasterka retro oo leh slots ballaaran. Ku habboon bagels iyo rooti ballaaran.",
    price: 28.00,
    image: "/images/products/small-appliances/retro-toaster.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 25,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 98,
    originalPrice: 35.00,
  },
  {
    id: "sa-004",
    name_en: "Electric Rice Cooker",
    name_so: "Qabka Bariiska",
    description_en: "Digital rice cooker with keep-warm function. Perfect fluffy rice every time.",
    description_so: "Qabka bariiska elektarooniga oo leh hawl la ilaaliyo. Bariis wanaagsan maalin kasta.",
    price: 55.00,
    image: "/images/products/small-appliances/rice-cooker.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 20,
    featured: true,
    active: true,
    rating: 4.9,
    reviewCount: 234,
    originalPrice: 70.00,
  },
  {
    id: "sa-005",
    name_en: "Espresso Machine",
    name_so: "Makiinada Kahada",
    description_en: "Compact espresso machine with milk frother. Barista-quality coffee at home.",
    description_so: "Makiinada kahada oo leh milk frother. Kahada wanaagsan guriga.",
    price: 120.00,
    image: "/images/products/small-appliances/espresso-machine.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 8,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 145,
    originalPrice: 150.00,
  },
  {
    id: "sa-006",
    name_en: "Food Processor 8-Cup",
    name_so: "Makiinada Cuntada",
    description_en: "Multi-function food processor with chopping, slicing, and shredding blades.",
    description_so: "Makiinada cuntada oo leh blades kala duwan. Ku habboon cunto karinta.",
    price: 75.00,
    image: "/images/products/small-appliances/food-processor.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 12,
    featured: false,
    active: true,
    rating: 4.6,
    reviewCount: 89,
    originalPrice: 95.00,
  },
  {
    id: "sa-007",
    name_en: "Stand Mixer 5Qt",
    name_so: "Mixerka Guurka",
    description_en: "Professional stand mixer with multiple attachments. Perfect for baking.",
    description_so: "Mixerka guurka oo leh attachments kala duwan. Ku habboon baking.",
    price: 180.00,
    image: "/images/products/small-appliances/stand-mixer.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 6,
    featured: true,
    active: true,
    rating: 4.9,
    reviewCount: 178,
    originalPrice: 220.00,
  },
  {
    id: "sa-008",
    name_en: "Air Fryer 5L",
    name_so: "Air Fryerka",
    description_en: "Digital air fryer with touchscreen. Healthier frying with 80% less oil.",
    description_so: "Air fryerka elektarooniga oo leh touchscreen. Cunto karinta oo caafimaad leh.",
    price: 85.00,
    image: "/images/products/small-appliances/air-fryer.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 18,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 256,
    originalPrice: 110.00,
  },
  {
    id: "sa-009",
    name_en: "Slow Cooker 6Qt",
    name_so: "Qabka Cuntada Degdeg",
    description_en: "Digital slow cooker with programmable timer. Perfect for stews and soups.",
    description_so: "Qabka cuntada elektarooniga oo leh timer. Ku habboon stews iyo soups.",
    price: 45.00,
    image: "/images/products/small-appliances/slow-cooker.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 15,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 134,
    originalPrice: 55.00,
  },
  {
    id: "sa-010",
    name_en: "Centrifugal Juicer",
    name_so: "Juicerka",
    description_en: "Powerful centrifugal juicer with large feed chute. Fresh juice in seconds.",
    description_so: "Juicerka oo leh feed chute ballaaran. Juice cusub ilbiriqsi.",
    price: 58.00,
    image: "/images/products/small-appliances/centrifugal-juicer.png",
    category_id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    category: "Small Appliances",
    stock: 12,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 78,
    originalPrice: 75.00,
  },

  // ===== TABLEWARE (10 products) =====
  {
    id: "tw-001",
    name_en: "Dinner Plate Set 6-Piece",
    name_so: "Biramka 6 Qaybood",
    description_en: "Elegant ceramic dinner plates with matte black finish and red gold rim.",
    description_so: "Biramka biramka ah oo 6 qaybood ah. Mid wanaagsan oo leh rim gold ah.",
    price: 48.00,
    image: "/images/products/tableware/dinner-plate-set.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 20,
    featured: true,
    active: true,
    rating: 4.7,
    reviewCount: 156,
    originalPrice: 60.00,
  },
  {
    id: "tw-002",
    name_en: "Ceramic Bowls Set 4-Piece",
    name_so: "Biramka 4 Qaybood",
    description_en: "Set of 4 ceramic soup bowls in glossy black with red interior.",
    description_so: "Biramka biramka ah oo 4 qaybood ah. Mid wanaagsan oo leh interior red ah.",
    price: 32.00,
    image: "/images/products/tableware/ceramic-bowls-set.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 25,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 89,
    originalPrice: 40.00,
  },
  {
    id: "tw-003",
    name_en: "Coffee Mugs Set 4-Piece",
    name_so: "Koobka 4 Qaybood",
    description_en: "Set of 4 ceramic coffee mugs in matte black with red handles.",
    description_so: "Koobka biramka ah oo 4 qaybood ah. Mid wanaagsan oo leh handles red ah.",
    price: 25.00,
    image: "/images/products/tableware/coffee-mugs-set.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 30,
    featured: true,
    active: true,
    rating: 4.6,
    reviewCount: 203,
    originalPrice: 32.00,
  },
  {
    id: "tw-004",
    name_en: "Wine Glasses Set 6-Piece",
    name_so: "Koobka Wine 6 Qaybood",
    description_en: "Set of 6 crystal wine glasses with elegant red stem accents.",
    description_so: "Koobka wine ah oo 6 qaybood ah. Mid wanaagsan oo leh stem red ah.",
    price: 45.00,
    image: "/images/products/tableware/wine-glasses-set.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 15,
    featured: false,
    active: true,
    rating: 4.8,
    reviewCount: 78,
    originalPrice: 55.00,
  },
  {
    id: "tw-005",
    name_en: "Serving Platter Large",
    name_so: "Safkeeda Wayn",
    description_en: "Large rectangular ceramic serving platter with geometric pattern.",
    description_so: "Safkeeda wayn oo biramka ah. Mid wanaagsan oo leh pattern geometric ah.",
    price: 35.00,
    image: "/images/products/tableware/serving-platter.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 18,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 56,
    originalPrice: 45.00,
  },
  {
    id: "tw-006",
    name_en: "Cutlery Set 24-Piece",
    name_so: "Cutlery 24 Qaybood",
    description_en: "24-piece stainless steel cutlery set with black handles and red trim.",
    description_so: "Cutlery 24 qaybood oo birta ah. Mid wanaagsan oo leh handles black ah.",
    price: 55.00,
    image: "/images/products/tableware/cutlery-set.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 12,
    featured: true,
    active: true,
    rating: 4.7,
    reviewCount: 145,
    originalPrice: 70.00,
  },
  {
    id: "tw-007",
    name_en: "Salad Bowl Large",
    name_so: "Biramka Saladka",
    description_en: "Large ceramic salad bowl in deep red with black exterior.",
    description_so: "Biramka saladka oo biramka ah. Mid wanaagsan oo leh exterior black ah.",
    price: 28.00,
    image: "/images/products/tableware/salad-bowl.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 20,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 67,
    originalPrice: 35.00,
  },
  {
    id: "tw-008",
    name_en: "Dessert Plates Set 6-Piece",
    name_so: "Biramka Dessertka 6 Qaybood",
    description_en: "Set of 6 small dessert plates in black with red floral pattern.",
    description_so: "Biramka dessertka ah oo 6 qaybood ah. Mid wanaagsan oo leh pattern floral ah.",
    price: 22.00,
    image: "/images/products/tableware/dessert-plates.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 25,
    featured: false,
    active: true,
    rating: 4.3,
    reviewCount: 45,
    originalPrice: 28.00,
  },
  {
    id: "tw-009",
    name_en: "Glass Tumblers Set 6-Piece",
    name_so: "Tumblers 6 Qaybood",
    description_en: "Set of 6 glass tumblers with elegant red tinted base.",
    description_so: "Tumblers ah oo 6 qaybood ah. Mid wanaagsan oo leh base red ah.",
    price: 18.00,
    image: "/images/products/tableware/glass-tumblers.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 30,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 89,
    originalPrice: 24.00,
  },
  {
    id: "tw-010",
    name_en: "Teapot Set with Cups",
    name_so: "Teapot Set",
    description_en: "Ceramic teapot with 4 matching cups in elegant black and red design.",
    description_so: "Teapot oo leh 4 koob. Mid wanaagsan oo leh design black iyo red ah.",
    price: 42.00,
    image: "/images/products/tableware/teapot-set.png",
    category_id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    category: "Tableware",
    stock: 15,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 112,
    originalPrice: 55.00,
  },

  // ===== ELECTRONICS (10 products) =====
  {
    id: "el-001",
    name_en: "Smart TV 55-Inch",
    name_so: "TV Smart 55-Inch",
    description_en: "55-inch smart TV with ultra-thin bezel. 4K resolution with smart features.",
    description_so: "TV smart oo 55-inch ah. 4K resolution oo leh features smart ah.",
    price: 450.00,
    image: "/images/products/electronics/smart-tv.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 5,
    featured: true,
    active: true,
    rating: 4.9,
    reviewCount: 234,
    originalPrice: 550.00,
  },
  {
    id: "el-002",
    name_en: "Bluetooth Speaker Portable",
    name_so: "Speaker Bluetooth",
    description_en: "Portable Bluetooth speaker with powerful bass and 12-hour battery life.",
    description_so: "Speaker Bluetooth oo leh bass xoog iyo battery 12 saac.",
    price: 45.00,
    image: "/images/products/electronics/bluetooth-speaker.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 25,
    featured: true,
    active: true,
    rating: 4.6,
    reviewCount: 189,
    originalPrice: 55.00,
  },
  {
    id: "el-003",
    name_en: "Wireless Headphones",
    name_so: "Headphones Wireless",
    description_en: "Over-ear wireless headphones with active noise cancellation.",
    description_so: "Headphones wireless oo leh noise cancellation.",
    price: 85.00,
    image: "/images/products/electronics/wireless-headphones.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 15,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 256,
    originalPrice: 110.00,
  },
  {
    id: "el-004",
    name_en: "Soundbar 2.1 Channel",
    name_so: "Soundbar",
    description_en: "Slim soundbar with built-in subwoofer. Immersive home theater audio.",
    description_so: "Soundbar oo leh subwoofer. Audio wanaagsan guriga.",
    price: 120.00,
    image: "/images/products/electronics/soundbar.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 10,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 78,
    originalPrice: 150.00,
  },
  {
    id: "el-005",
    name_en: "Streaming Device 4K",
    name_so: "Streaming Device",
    description_en: "Compact 4K streaming device with all major apps included.",
    description_so: "Streaming device 4K oo leh apps dhan.",
    price: 35.00,
    image: "/images/products/electronics/streaming-device.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 20,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 145,
    originalPrice: 45.00,
  },
  {
    id: "el-006",
    name_en: "Gaming Console",
    name_so: "Gaming Console",
    description_en: "Modern gaming console with powerful graphics and fast loading.",
    description_so: "Gaming console oo leh graphics xoog iyo loading degdeg.",
    price: 380.00,
    image: "/images/products/electronics/gaming-console.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 6,
    featured: true,
    active: true,
    rating: 4.9,
    reviewCount: 312,
    originalPrice: 450.00,
  },
  {
    id: "el-007",
    name_en: "Digital Camera Mirrorless",
    name_so: "Camera Digital",
    description_en: "Compact mirrorless digital camera with interchangeable lens system.",
    description_so: "Camera digital oo leh lens interchangeable.",
    price: 550.00,
    image: "/images/products/electronics/digital-camera.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 4,
    featured: false,
    active: true,
    rating: 4.8,
    reviewCount: 89,
    originalPrice: 700.00,
  },
  {
    id: "el-008",
    name_en: "Smartwatch Premium",
    name_so: "Smartwatch",
    description_en: "Premium smartwatch with health tracking and GPS features.",
    description_so: "Smartwatch oo leh health tracking iyo GPS.",
    price: 150.00,
    image: "/images/products/electronics/smartwatch.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 12,
    featured: true,
    active: true,
    rating: 4.7,
    reviewCount: 203,
    originalPrice: 190.00,
  },
  {
    id: "el-009",
    name_en: "Portable Charger 20000mAh",
    name_so: "Power Bank",
    description_en: "Slim portable power bank with fast charging support for all devices.",
    description_so: "Power bank oo leh fast charging dhan.",
    price: 28.00,
    image: "/images/products/electronics/portable-charger.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 30,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 167,
    originalPrice: 35.00,
  },
  {
    id: "el-010",
    name_en: "LED Desk Lamp Modern",
    name_so: "Lamp Desk LED",
    description_en: "Modern LED desk lamp with adjustable brightness and color temperature.",
    description_so: "Lamp desk LED oo leh brightness adjustable.",
    price: 32.00,
    image: "/images/products/electronics/led-desk-lamp.png",
    category_id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    category: "Electronics",
    stock: 20,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 78,
    originalPrice: 40.00,
  },

  // ===== HOME APPLIANCES (10 products) =====
  {
    id: "ha-001",
    name_en: "Refrigerator French Door",
    name_so: "Refrigerator",
    description_en: "Modern French door refrigerator with large capacity and energy efficiency.",
    description_so: "Refrigerator French door oo leh capacity weyn.",
    price: 850.00,
    image: "/images/products/home-appliances/refrigerator.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 3,
    featured: true,
    active: true,
    rating: 4.9,
    reviewCount: 145,
    originalPrice: 1000.00,
  },
  {
    id: "ha-002",
    name_en: "Washing Machine Front Load",
    name_so: "Mashiinka Dharka",
    description_en: "Front-loading washing machine with multiple wash programs.",
    description_so: "Mashiinka dharka oo leh programs badan.",
    price: 450.00,
    image: "/images/products/home-appliances/washing-machine.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 5,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 189,
    originalPrice: 550.00,
  },
  {
    id: "ha-003",
    name_en: "Microwave Oven Digital",
    name_so: "Microwave",
    description_en: "Digital microwave oven with multiple cooking presets and quick heat.",
    description_so: "Microwave digital oo leh presets badan.",
    price: 85.00,
    image: "/images/products/home-appliances/microwave-oven.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 15,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 134,
    originalPrice: 110.00,
  },
  {
    id: "ha-004",
    name_en: "Vacuum Cleaner Cordless",
    name_so: "Vacuum Cordless",
    description_en: "Cordless stick vacuum with powerful suction and long battery life.",
    description_so: "Vacuum cordless oo leh suction xoog.",
    price: 180.00,
    image: "/images/products/home-appliances/vacuum-cleaner.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 8,
    featured: true,
    active: true,
    rating: 4.7,
    reviewCount: 203,
    originalPrice: 220.00,
  },
  {
    id: "ha-005",
    name_en: "Dishwasher Built-In",
    name_so: "Dishwasher",
    description_en: "Built-in dishwasher with multiple wash cycles and energy star rating.",
    description_so: "Dishwasher oo leh cycles badan.",
    price: 380.00,
    image: "/images/products/home-appliances/dishwasher.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 4,
    featured: false,
    active: true,
    rating: 4.6,
    reviewCount: 78,
    originalPrice: 450.00,
  },
  {
    id: "ha-006",
    name_en: "Air Conditioner Split",
    name_so: "Air Conditioner",
    description_en: "Split air conditioner with cooling and heating functions.",
    description_so: "Air conditioner oo leh cooling iyo heating.",
    price: 350.00,
    image: "/images/products/home-appliances/air-conditioner.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 6,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 89,
    originalPrice: 420.00,
  },
  {
    id: "ha-007",
    name_en: "Water Dispenser Hot/Cold",
    name_so: "Water Dispenser",
    description_en: "Hot and cold water dispenser with child safety lock.",
    description_so: "Water dispenser oo leh hot iyo cold.",
    price: 120.00,
    image: "/images/products/home-appliances/water-dispenser.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 10,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 56,
    originalPrice: 150.00,
  },
  {
    id: "ha-008",
    name_en: "Steam Iron Professional",
    name_so: "Iron Steam",
    description_en: "Professional steam iron with anti-drip and auto shut-off features.",
    description_so: "Iron steam oo leh anti-drip.",
    price: 45.00,
    image: "/images/products/home-appliances/steam-iron.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 20,
    featured: false,
    active: true,
    rating: 4.3,
    reviewCount: 145,
    originalPrice: 55.00,
  },
  {
    id: "ha-009",
    name_en: "Ceiling Fan Modern",
    name_so: "Fan Ceiling",
    description_en: "Modern ceiling fan with remote control and LED light kit.",
    description_so: "Fan ceiling oo leh remote control.",
    price: 75.00,
    image: "/images/products/home-appliances/ceiling-fan.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 12,
    featured: false,
    active: true,
    rating: 4.2,
    reviewCount: 67,
    originalPrice: 90.00,
  },
  {
    id: "ha-010",
    name_en: "Water Heater Tankless",
    name_so: "Water Heater",
    description_en: "Tankless electric water heater with digital temperature control.",
    description_so: "Water heater tankless oo leh digital control.",
    price: 280.00,
    image: "/images/products/home-appliances/water-heater.png",
    category_id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    category: "Home Appliances",
    stock: 5,
    featured: false,
    active: true,
    rating: 4.6,
    reviewCount: 34,
    originalPrice: 350.00,
  },

  // ===== PHONES & TABLETS (10 products) =====
  {
    id: "pt-001",
    name_en: "Smartphone Android Pro",
    name_so: "Smartphone Android",
    description_en: "Premium Android smartphone with 128GB storage and dual camera system.",
    description_so: "Smartphone Android oo leh 128GB storage.",
    price: 320.00,
    image: "/images/products/phones-tablets/smartphone.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 15,
    featured: true,
    active: true,
    rating: 4.8,
    reviewCount: 289,
    originalPrice: 380.00,
  },
  {
    id: "pt-002",
    name_en: "Tablet 10-Inch HD",
    name_so: "Tablet 10-Inch",
    description_en: "10-inch tablet with HD display and long battery life.",
    description_so: "Tablet 10-inch oo leh HD display.",
    price: 180.00,
    image: "/images/products/phones-tablets/tablet.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 12,
    featured: true,
    active: true,
    rating: 4.6,
    reviewCount: 145,
    originalPrice: 220.00,
  },
  {
    id: "pt-003",
    name_en: "Phone Case Protective",
    name_so: "Phone Case",
    description_en: "Protective phone case with shock absorption and sleek design.",
    description_so: "Phone case oo leh shock absorption.",
    price: 15.00,
    image: "/images/products/phones-tablets/phone-case.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 50,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 89,
    originalPrice: 20.00,
  },
  {
    id: "pt-004",
    name_en: "Screen Protector Tempered",
    name_so: "Screen Protector",
    description_en: "Tempered glass screen protector with 9H hardness rating.",
    description_so: "Screen protector tempered glass.",
    price: 8.00,
    image: "/images/products/phones-tablets/screen-protector.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 100,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 234,
    originalPrice: 12.00,
  },
  {
    id: "pt-005",
    name_en: "Wireless Earbuds Pro",
    name_so: "Earbuds Wireless",
    description_en: "Wireless earbuds with active noise cancellation and premium sound.",
    description_so: "Earbuds wireless oo leh noise cancellation.",
    price: 65.00,
    image: "/images/products/phones-tablets/wireless-earbuds.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 25,
    featured: true,
    active: true,
    rating: 4.7,
    reviewCount: 178,
    originalPrice: 85.00,
  },
  {
    id: "pt-006",
    name_en: "Phone Charger Fast",
    name_so: "Charger Fast",
    description_en: "Fast charging cable and adapter for all smartphone models.",
    description_so: "Charger fast oo leh cable iyo adapter.",
    price: 18.00,
    image: "/images/products/phones-tablets/phone-charger.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 40,
    featured: false,
    active: true,
    rating: 4.6,
    reviewCount: 156,
    originalPrice: 22.00,
  },
  {
    id: "pt-007",
    name_en: "Tablet Stand Adjustable",
    name_so: "Tablet Stand",
    description_en: "Adjustable tablet stand with multiple viewing angles.",
    description_so: "Tablet stand oo leh angles badan.",
    price: 25.00,
    image: "/images/products/phones-tablets/tablet-stand.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 30,
    featured: false,
    active: true,
    rating: 4.4,
    reviewCount: 78,
    originalPrice: 32.00,
  },
  {
    id: "pt-008",
    name_en: "Bluetooth Keyboard",
    name_so: "Keyboard Bluetooth",
    description_en: "Portable Bluetooth keyboard for tablets and smartphones.",
    description_so: "Keyboard Bluetooth oo leh tablets iyo smartphones.",
    price: 35.00,
    image: "/images/products/phones-tablets/bluetooth-keyboard.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 20,
    featured: false,
    active: true,
    rating: 4.5,
    reviewCount: 67,
    originalPrice: 45.00,
  },
  {
    id: "pt-009",
    name_en: "Power Bank 10000mAh",
    name_so: "Power Bank",
    description_en: "Portable power bank with dual USB ports and LED indicator.",
    description_so: "Power bank oo leh dual USB ports.",
    price: 22.00,
    image: "/images/products/phones-tablets/power-bank.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 35,
    featured: false,
    active: true,
    rating: 4.6,
    reviewCount: 145,
    originalPrice: 28.00,
  },
  {
    id: "pt-010",
    name_en: "Car Phone Holder",
    name_so: "Phone Holder Car",
    description_en: "Universal car phone holder with 360-degree rotation.",
    description_so: "Phone holder car oo leh rotation 360.",
    price: 12.00,
    image: "/images/products/phones-tablets/car-phone-holder.png",
    category_id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    category: "Phones & Tablets",
    stock: 45,
    featured: false,
    active: true,
    rating: 4.3,
    reviewCount: 89,
    originalPrice: 16.00,
  },
];

export const categories = [
  {
    id: "3bc634d7-b8af-4b6b-8370-3861cbb589b7",
    name_en: "Cookware",
    name_so: "Qabka Cuntada",
    slug: "cookware",
    image: "/images/categories/category-cookware.png",
  },
  {
    id: "97457fe7-b093-467c-ac3d-bb1c1ae6f6dc",
    name_en: "Small Appliances",
    name_so: "Qalabka Yar",
    slug: "small-appliances",
    image: "/images/categories/category-small-appliances.png",
  },
  {
    id: "332b4021-fa30-4d04-b41a-55eda6a91f33",
    name_en: "Tableware",
    name_so: "Safkeeda",
    slug: "tableware",
    image: "/images/categories/category-tableware.png",
  },
  {
    id: "fdada9bc-98a2-4985-afc9-582f60b4a504",
    name_en: "Electronics",
    name_so: "Elektarooniga",
    slug: "electronics",
    image: "/images/categories/category-electronics.png",
  },
  {
    id: "095c9113-c68f-40a9-a18f-4cbdd5825ba0",
    name_en: "Home Appliances",
    name_so: "Qalabka Guriga",
    slug: "home-appliances",
    image: "/images/categories/category-home-appliances.png",
  },
  {
    id: "cd52de47-2791-482a-b0dc-d22b25fc8580",
    name_en: "Phones & Tablets",
    name_so: "Gacamaha & Taabblayada",
    slug: "phones-tablets",
    image: "/images/categories/category-phones-tablets.png",
  },
];

export const featuredProducts = products.filter((p) => p.featured);

export function getProductById(id: string) {
  return products.find((p) => p.id === id) || null;
}

export function getProductsByCategory(categoryId: string) {
  return products.filter((p) => p.category_id === categoryId);
}

export function getCategoryById(id: string) {
  return categories.find((c) => c.id === id) || null;
}

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug) || null;
}